name: Lint

on: push

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Set up protoc
      run: |
        curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v3.15.5/protoc-3.15.5-linux-x86_64.zip"
        unzip protoc-3.15.5-linux-x86_64.zip -d $HOME/.local
        go get -v google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint
      run: |
        export PATH="$PATH:$HOME/.local/bin"
        make lint
